version: "3.5"
services:
  npm-registry:
    image: verdaccio/verdaccio:beta
    networks:
      - proxy
    volumes:
      - npm-registry:/verdaccio
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.enable=true"
        - "traefik.port=4873"
        - "traefik.frontend.rule=Host:npm-registry.thomrick.com"
networks:
  proxy:
    name: proxy
