version: "3"
services:
  traefik:
    image: traefik
    command:
      - "--web"
      - "--docker"
      - "--docker.swarmmode"
      - "--docker.domain=docker.local"
      - "--docker.watch"
      - "--logLevel=DEBUG"
    networks:
      - proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/dev/null:/traefik.toml"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
networks:
  proxy:
    external:
      name: proxy