version: "3"
services:
  portainer:
    image: portainer/portainer
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/portainer:/data"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:portainer.thomrick.com"
networks:
  proxy:
    external:
      name: proxy